# Generated by Django 3.0.4 on 2020-06-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='min_steps',
            field=models.IntegerField(null=True),
        ),
    ]
